import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { notFound } from "next/navigation";
import { Footer } from "@/components/footer";
import { LivePreview } from "@/components/live-preview";
import { Navbar } from "@/components/navbar";
import { ExperienceControls } from "@/components/experience-controls";
import { getDictionary, isLocale, locales } from "@/lib/i18n";
import { getProject, projects } from "@/lib/projects";

export function generateStaticParams() { return locales.flatMap((locale) => projects.map((project) => ({ locale, slug: project.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const project = getProject(slug); if (!project) return {}; return { title: `${project.title} | Adonix Digital`, description: project.description[locale === "ar" ? "ar" : "en"], alternates: { canonical: `/${locale}/work/${slug}`, languages: { ar: `/ar/work/${slug}`, en: `/en/work/${slug}` } } }; }
export default async function CaseStudy({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale: value, slug } = await params; if (!isLocale(value)) notFound(); const locale = value; const project = getProject(slug); if (!project) notFound(); const t = await getDictionary(locale); const next = projects[(projects.findIndex((p) => p.slug === slug) + 1) % projects.length]; return <main><ExperienceControls locale={locale}/><Navbar locale={locale} t={t}/><section className="case-hero shell"><Link href={`/${locale}/#work`} className="back-link"><ArrowLeft size={17}/>{t.case.back}</Link><p className="eyebrow">{t.work.categories[project.category]} · {project.year}</p><h1>{project.title}</h1><p>{project.description[locale]}</p><a href={project.url} target="_blank" rel="noreferrer" className="button button-solid">{t.work.visit}<ArrowUpRight size={17}/></a></section><section className="case-details shell"><div><p className="eyebrow">{t.case.overview}</p><h2>{project.title}</h2><p>{project.description[locale]}</p></div><dl><div><dt>{t.case.country}</dt><dd>{project.country}</dd></div><div><dt>{t.case.year}</dt><dd>{project.year}</dd></div><div><dt>{t.case.technology}</dt><dd>{project.technologies.join(" · ")}</dd></div></dl></section><section className="case-split shell"><div><p className="eyebrow">{t.case.challenge}</p><h2>{locale === "ar" ? "تجربة قوية بلا تعقيد." : "An experience that makes its value obvious."}</h2><p>{locale === "ar" ? "صممنا هذا المنتج ليعكس طموح العلامة التجارية ويوصل المستخدم إلى الخطوة التالية بلا تشتيت." : "We designed this product to reflect the brand’s ambition and move people to the next step without distraction."}</p></div><div><p className="eyebrow">{t.case.solution}</p><h2>{locale === "ar" ? "تصميم مقصود، أداء ملحوظ." : "Intentional design, visible performance."}</h2><p>{locale === "ar" ? "كل قرار في الواجهة يخدم الوضوح والثقة والتفاعل السلس على كل جهاز." : "Every interface decision serves clarity, confidence and fluid interaction on every device."}</p></div></section><section className="case-features shell"><p className="eyebrow">{t.case.features}</p><div>{project.features[locale].map((feature, index) => <div key={feature}><span>0{index + 1}</span>{feature}</div>)}</div></section><section className="case-score shell"><p className="eyebrow">{locale === "ar" ? "جاهز للأداء" : "Performance-ready"}</p><div><strong>98</strong><span>{locale === "ar" ? "بنية سريعة وتجربة متجاوبة" : "Fast architecture, responsive experience"}</span></div></section><section className="case-live shell"><div className="section-heading"><p className="eyebrow">{t.case.live}</p><h2>{project.title}</h2></div><LivePreview url={project.url} title={project.title} t={t}/></section><Link href={`/${locale}/work/${next.slug}`} className="next-project"><span>{t.case.next}</span><strong>{next.title}</strong><ArrowUpRight/></Link><Footer locale={locale} t={t}/></main>; }
